apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-13
  namespace: production
  labels:
    app: postgres
spec:
  serviceName: "postgres-13"
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.role
                operator: In
                values:
                - datebase
      containers:
        - name: postgres-13
          image: devsadds/postgres:13.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres-13-01"
          envFrom:
          - configMapRef:
              name: postgres-config
      volumes:
        - hostPath:
            path: "/docker-compose-local/volumes/postgres-13-01"
          name: postgres-13-01



